Merge main into v2
hyperlane-xyz/hyperlane-monorepo pull request #1280
Opened 2022-11-15 19:17 UTC by asaj

### Description

_What's included in this PR?_

### Drive-by changes

_Are there any minor or drive-by changes also included?_

### Related issues

- Fixes #[issue number here]

### Backward compatibility

_Are these changes backward compatible?_

Yes
No

_Are there any infrastructure implications, e.g. changes that would prohibit deploying older commits using this infra tooling?_

None
Yes

### Testing

_What kind of testing have these changes undergone?_

None
Manual
Unit Tests

2022-11-21 17:25 UTC, asaj commented on rust-toolchain
> +channel = "1.65"
Do not resolve:
- need to squash non-main commits so as not to pollute version history

2022-11-22 20:14 UTC, mattiecnvr commented
One thing I am noticing very quickly about this diff to review is that it shows what was changed in `v2` but it does not show what was not included from `main` so while I will review this it will be very hard for me to notice if something that was in a commit from `main` was excluded when it should not have been in this merge.

2022-11-23 14:41 UTC, tkporter approved these changes
The diff is so big that I can't say I did a very deep review- nothing drastic stands out to me though

2022-11-23 14:41 UTC, tkporter commented on rust/agents/scraper/src/agent.rs
> +            // let ctx = || format!("Loading chain {}", chain_name);
I'm guessing you intended to come back to this & line 50?

2022-11-23 18:01 UTC, mattiecnvr requested changes
See review PR as well

2022-11-28 14:35 UTC, asaj commented on rust/helm/scraper/templates/configmap.yaml
>  data:
Yeah I'm planning on addressing this in a future PR

2022-11-28 16:47 UTC, merged