Rm basegoerli and moonbasealpha
hyperlane-xyz/hyperlane-monorepo pull request #3256
Opened 2024-02-13 17:18 UTC by tkporter

### Description

### Drive-by changes

### Related issues

### Backward compatibility

### Testing

2024-02-13 17:30 UTC, jmrossy requested changes
Can we remove it from Chains and chainmetadata as well please? Otherwise the metadata health checks will continue to fail

2024-02-14 09:40 UTC, tkporter commented
@jmrossy great points, done :)

2024-02-14 12:44 UTC, paulbalaji approved these changes
:shipit:

2024-02-14 16:00 UTC, jmrossy approved these changes

2024-02-14 16:08 UTC, merged