fix(cli): hide large configs in core read command
hyperlane-xyz/hyperlane-monorepo pull request #4192
Opened 2024-07-23 20:12 UTC by ltyu

### Description
This PR adds a helper function that logs the config terminal "preview", _only_ if the number of lines is < 250 for `hyperlane core read`.

### Related issues
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4191

Yes

### Testing
Manual
- `yarn build && yarn hyperlane core read --mailbox 0x2f9DB5616fa3fAd1aB06cB2C906830BA63d135e3  --chain fraxtal `
- And tried with a deployed one to test out lines < 250

2024-07-23 20:27 UTC, nbayindirli commented on typescript/cli/src/commands/core.ts
> +      logYamlIfUnderMaxLines(coreConfig, 250);
store 250 as a const like `MAX_READ_LINE_OUTPUT` to be shared between core and warp

2024-07-23 20:27 UTC, nbayindirli requested changes
need to apply to `warp` as well

2024-07-23 20:43 UTC, ltyu commented
> need to apply to `warp` as well

@nbayindirli Agreed. im going to do this in 4.3 release.
- It requires a little bit more thought since we need to always write to output parameter, which is optional right now. We may end up doing the same as Core, but going to leave that to discussion to decide if its desirable.
- warp configs are arguably not as big. At least they can fit on the screen

2024-07-29 16:53 UTC, nbayindirli commented on typescript/cli/src/utils/files.ts
> +  margin = 2,
```suggestion
  maxLines: number = MAX_READ_LINE_OUTPUT,
  margin: number = 2,
```

2024-07-29 16:53 UTC, nbayindirli approved these changes

2024-07-29 16:54 UTC, nbayindirli commented on typescript/cli/src/commands/core.ts
> +      logYamlIfUnderMaxLines(coreConfig, MAX_READ_LINE_OUTPUT);
with the below update, just
```suggestion
      logYamlIfUnderMaxLines(coreConfig);
```

2024-07-29 16:54 UTC, nbayindirli approved these changes

2024-07-29 17:50 UTC, merged