fix(contracts): InterchainAccountRouter minor audit remediation
hyperlane-xyz/hyperlane-monorepo pull request #4581
Opened 2024-09-27 12:40 UTC by aroralanuk

### Description

### Drive-by changes

### Related issues

### Backward compatibility

### Testing

2024-10-01 19:29 UTC, yorhodes approved these changes
my mental model for events is to surface data that is cumulative/not a constant time view call
dont feel strongly but this seems superfluous
I dont think we will ever build an indexer for these?

2024-10-01 19:29 UTC, yorhodes commented on solidity/contracts/middleware/InterchainAccountRouter.sol
imo it would be quite simplifying if we just treated this like a normal router
theres not really a big cost of just deploying your own if you cant enroll on an existing set

2024-10-01 19:29 UTC, yorhodes commented on solidity/contracts/middleware/InterchainAccountRouter.sol
but probably not the place to make this change

2024-10-04 17:52 UTC, aroralanuk commented
> my mental model for events is to surface data that is cumulative/not a constant time view call dont feel strongly but this seems superfluous I dont think we will ever build an indexer for these?

is hookset not something we can use in the validator if say the merkle hook gets updated in the future?

2024-10-09 14:05 UTC, yorhodes requested changes
all lgtm except the only initializing change, please revert

2024-10-23 19:44 UTC, aroralanuk commented on solidity/contracts/middleware/InterchainAccountRouter.sol
> +    }
fixed

2024-10-28 17:36 UTC, yorhodes approved these changes

2024-10-29 11:12 UTC, merged