feat: support safe tx parsing for zksync chains
hyperlane-xyz/hyperlane-monorepo pull request #5042
Opened 2024-12-18 14:58 UTC by paulbalaji

### Description

1. correctly generate core config for zksync chains
	- copied from `pb/zksync` https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/pb/zksync/typescript/infra/config/environments/mainnet3/core.ts
	- note the storage aggregation ism was not around when doing the first zksync chain deploys, and we haven't gone back and updated the config generation yet to include this
	- required so we infer the correct config for zksync changes and don't assume it's the same as non-zksync chains

2. update ISM reader to return storagemultisigism types on zksync
	- since static ISMs are not supported on zksync
	- the moduleType is the same, so the reader has to determine if it's static/storage
	- note: at the moment on non-zksync we assume it's a static multisig/aggregation ISM
	- required so we correctly compare the config vs onchain config

### Drive-by changes

### Related issues

### Backward compatibility

### Testing

- these changes were used to verify SAFE txs for the last couple of batches
- the config changes have also been used in production on zksync chains since October 23rd 2024 [`26d198a` (#4761)](https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4761/commits/26d198a18fe0dce0ebf28ab75c32788e7104e2fc#diff-d4db62438f3fd9acf24be52093e81d126292859f9f48c81aa1704d41fe8ddf1a)

2024-12-20 21:56 UTC, cmcewen requested changes
Tests not all passing

2025-01-10 14:29 UTC, tkporter approved these changes
you can dismiss requested changes

2025-01-10 14:29 UTC, tkporter commented on typescript/infra/config/environments/mainnet3/core.ts
> +    const defaultZkSyncIsm: RoutingIsmConfig = {
nit: do we need to build this when isZkSyncChain is false? not a big deal if it's clunky to only do it conditionally

2025-01-10 14:29 UTC, tkporter commented on typescript/infra/config/environments/testnet4/core.ts
is this the exact same logic as mainnet3? wonder if there's an easy opportunity for consolidation

2025-01-10 14:29 UTC, tkporter commented on typescript/sdk/src/ism/EvmIsmReader.ts
> +      ? IsmType.STORAGE_AGGREGATION
if we have storage aggregations now, do we still need to have the weird setup for avoiding aggregation hooks / ISMs?

2025-01-10 14:53 UTC, paulbalaji commented on typescript/sdk/src/ism/EvmIsmReader.ts
> +      ? IsmType.STORAGE_AGGREGATION
I believe we have aggregation isms but not aggregation hooks, so at least that can be updated. But I would prefer to do that in a separate PR at the time we actually enact those changes onchain, otherwise we'll get the checker complaining

2025-01-10 15:15 UTC, paulbalaji commented on typescript/infra/config/environments/testnet4/core.ts
yup it is - it's almost identical except for the protocol fee. mainnet3 set to 0 wei, testnet4 is 1 wei

2025-01-10 17:15 UTC, merged