feat: bump relayer memory usage to 20GB, add concurrency to agent deploys
hyperlane-xyz/hyperlane-monorepo pull request #5063
Opened 2024-12-20 21:46 UTC by tkporter

### Description

- Makes the relayer request 20GB of memory, forcing relayers to have their own node in our bigger node pool (capacity 29 GB)
- Driveby to use G (Gigabytes) instead of Gi (Gibibytes) to match what GCP uses in their UI, also a bit more intuitive
- Added a `--concurrency <num>` flag that can be used when deploying agents. Especially useful when releasing to all validators, which we have tons of now.
- Concurrently refetching remote repositories on helm poses issues, so I made this not happen by default anymore. It's not configurable at the CLI level to enable it, but we have the ability to easily add it later. Because our agent deploy doesn't actually require any remote helm repos, it's not necessary 

### Drive-by changes

### Related issues

### Backward compatibility

### Testing

2024-12-20 21:53 UTC, cmcewen requested changes
Tests not passing

2024-12-20 22:04 UTC, daniel-savu approved these changes

2024-12-21 01:06 UTC, paulbalaji approved these changes

2024-12-26 15:26 UTC, cmcewen approved these changes

2024-12-26 16:14 UTC, merged